baseURL = 'https://neurotechhub.github.io/'
languageCode = 'en-us'
title = 'NeuroTechHub'
theme = 'neurotech-theme'

[params]
  description = "Building the future of neurotech together"
  author = "NeuroTechHub Team"
  [[params.meta]]
  favicon = false
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Talks"
    url = "/talks/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github-dark"
    codeFences = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
